export const typeColors: Record<string, string> = {
    Fire: "bg-red-400 ",
    Water: "bg-blue-400",
    Grass: "bg-green-400",
    Electric: "bg-yellow-300",
    Poison: "bg-purple-500",
    Flying: "bg-sky-300",
    Ground: "bg-amber-600",
    Rock: "bg-stone-500",
    Fighting: "bg-red-700",
    Psychic: "bg-pink-500",
    Bug: "bg-lime-500",
    Dragon: "bg-indigo-600",
    Fairy: "bg-pink-300",
    Ice: "bg-cyan-300",
    Ghost: "bg-violet-700",
    Dark: "bg-gray-700",
    Steel: "bg-slate-400",
    Normal: "bg-zinc-400",
  };